UnicoreApiUrl: https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core
Environment:
  PreRunCommand:
    Command: > 
      module load Stages/2022 GCCcore/.11.2.0 GCC/11.2.0 cuDNN/8.3.1.22-CUDA-11.5 Python/3.9.6;
      source /p/project/deepacf/maelstrom/grau1/ap3_env/bin/activate;
    ExecuteOnLoginNode: False
  Variables:
    GIT_PYTHON_REFRESH: quiet
Resources:
  Queue: develbooster
  Nodes: 1
Exclude:
  - "*.sif"
  - "figures"
  - "saved_model"
  - README.md

